"""Prompts package initialization."""
from src.prompts.prompt_templates import (
    DRAW_REQ_PROMPT_SYSTEM_TEMPLATE,
    DRAW_REQ_PROMPT_TEMPLATE,
    DRAW_COMPYUI_PROMPT_SYSTEM_TEMPLATE,
    DRAW_COMPYUI_PROMPT_TEMPLATE,
    LEADER_TEMPLATE,
)

__all__ = [
    "DRAW_REQ_PROMPT_SYSTEM_TEMPLATE",
    "DRAW_REQ_PROMPT_TEMPLATE",
    "DRAW_COMPYUI_PROMPT_SYSTEM_TEMPLATE",
    "DRAW_COMPYUI_PROMPT_TEMPLATE",
    "LEADER_TEMPLATE",
]